export type RouteTextLanguage = "zh" | "en" | "ja";

export interface RouteTextTranslation {
  en: string;
  ja: string;
}

const weekdayTranslations: Record<string, { zh: string; en: string; ja: string }> = {
  日: { zh: "週日", en: "Sun", ja: "日" },
  一: { zh: "週一", en: "Mon", ja: "月" },
  二: { zh: "週二", en: "Tue", ja: "火" },
  三: { zh: "週三", en: "Wed", ja: "水" },
  四: { zh: "週四", en: "Thu", ja: "木" },
  五: { zh: "週五", en: "Fri", ja: "金" },
  六: { zh: "週六", en: "Sat", ja: "土" },
};

export const routeTextTranslations: Record<string, RouteTextTranslation> = {
  "6點出發，不休息(達仁7-11南迴前最後補給)\n壽卡前最後補給點\n（不集結休息）": {
    en: "6:00 departure, no group rest. Last supply before South Link: Daren 7-ELEVEN; last supply before Shouka; no regroup stop.",
    ja: "6時出発、休憩なし。南廻公路前の最後補給は達仁セブンイレブン、寿卡前の最後補給地点、集合休憩なし。",
  },
  "A4大鶯綠野景觀自行車道": { en: "A4 Daying Greenway Scenic Bikeway", ja: "A4大鶯緑野景観自転車道" },
  "七星潭": { en: "Qixingtan", ja: "七星潭" },
  "三義": { en: "Sanyi", ja: "三義" },
  "中原國小": { en: "Zhongyuan Elementary School", ja: "中原小学校" },
  "休息一天 自由行": { en: "Rest day, free time", ja: "休息日、自由行動" },
  "休息一日": { en: "Rest day", ja: "休息日" },
  "保力": { en: "Baoli", ja: "保力" },
  "光復": { en: "Guangfu", ja: "光復" },
  "公園路": { en: "Gongyuan Road", ja: "公園路" },
  "前鎮": { en: "Qianzhen", ja: "前鎮" },
  "北新國小": { en: "Beixin Elementary School", ja: "北新小学校" },
  "卑南": { en: "Beinan", ja: "卑南" },
  "南18": { en: "Tainan Route 18", ja: "南18線" },
  "南19": { en: "Tainan Route 19", ja: "南19線" },
  "南80": { en: "Tainan Route 80", ja: "南80線" },
  "南84": { en: "Tainan Route 84", ja: "南84線" },
  "南寮": { en: "Nanliao", ja: "南寮" },
  "南寮-頭前溪自行車道": { en: "Nanliao-Touqian River Bikeway", ja: "南寮-頭前溪自転車道" },
  "南投竹山": { en: "Zhushan, Nantou", ja: "南投竹山" },
  "南迴公路": { en: "South Link Highway", ja: "南廻公路" },
  "台1": { en: "Provincial Highway 1", ja: "台1線" },
  "台11": { en: "Provincial Highway 11", ja: "台11線" },
  "台13": { en: "Provincial Highway 13", ja: "台13線" },
  "台14": { en: "Provincial Highway 14", ja: "台14線" },
  "台16": { en: "Provincial Highway 16", ja: "台16線" },
  "台17": { en: "Provincial Highway 17", ja: "台17線" },
  "台19": { en: "Provincial Highway 19", ja: "台19線" },
  "台1丁": { en: "Provincial Highway 1D", ja: "台1丁線" },
  "台21": { en: "Provincial Highway 21", ja: "台21線" },
  "台26": { en: "Provincial Highway 26", ja: "台26線" },
  "台3": { en: "Provincial Highway 3", ja: "台3線" },
  "台3丙": { en: "Provincial Highway 3C", ja: "台3丙線" },
  "台3乙": { en: "Provincial Highway 3B", ja: "台3乙線" },
  "台4": { en: "Provincial Highway 4", ja: "台4線" },
  "台8": { en: "Provincial Highway 8", ja: "台8線" },
  "台9": { en: "Provincial Highway 9", ja: "台9線" },
  "台中": { en: "Taichung", ja: "台中" },
  "台中到苗栗高中": { en: "Taichung to Miaoli Senior High School", ja: "台中から苗栗高校" },
  "台南中西區": { en: "Tainan West Central District", ja: "台南中西区" },
  "台南市南區": { en: "Tainan South District", ja: "台南市南区" },
  "台東": { en: "Taitung", ja: "台東" },
  "台東到恆春國小": { en: "Taitung to Hengchun Elementary School", ja: "台東から恒春小学校" },
  "台體大國立臺灣體育運動大學": { en: "National Taiwan University of Sport", ja: "国立台湾体育運動大学" },
  "吉安": { en: "Ji'an", ja: "吉安" },
  "后科路": { en: "Houke Road", ja: "后科路" },
  "后里": { en: "Houli", ja: "后里" },
  "嘉義": { en: "Chiayi", ja: "嘉義" },
  "嘉義到溪南國小": { en: "Chiayi to Xinan Elementary School", ja: "嘉義から溪南小学校" },
  "國姓": { en: "Guoxing", ja: "国姓" },
  "國立臺灣體育運動大學": { en: "National Taiwan University of Sport", ja: "国立台湾体育運動大学" },
  "坪林": { en: "Pinglin", ja: "坪林" },
  "埔里": { en: "Puli", ja: "埔里" },
  "埔里到國立臺灣體育運動大學": { en: "Puli to National Taiwan University of Sport", ja: "埔里から国立台湾体育運動大学" },
  "培英國中": { en: "Peiying Junior High School", ja: "培英国中" },
  "報到與行前安全講習": { en: "Check-in and pre-ride safety briefing", ja: "受付と出発前安全講習" },
  "報到！行前安全講習(物資發放)": { en: "Check-in and pre-ride safety briefing (supply handout)", ja: "受付！出発前安全講習（物資配布）" },
  "壽卡": { en: "Shouka", ja: "寿卡" },
  "壽豐": { en: "Shoufeng", ja: "寿豊" },
  "大武": { en: "Dawu", ja: "大武" },
  "大溪": { en: "Daxi", ja: "大渓" },
  "大漢溪左岸自行車道": { en: "Dahan River Left Bank Bikeway", ja: "大漢溪左岸自転車道" },
  "大里": { en: "Dali", ja: "大里" },
  "太魯閣、新城": { en: "Taroko and Xincheng", ja: "太魯閣・新城" },
  "太魯閣遊客中心": { en: "Taroko Visitor Center", ja: "太魯閣ビジターセンター" },
  "太麻里": { en: "Taimali", ja: "太麻里" },
  "學甲": { en: "Xuejia", ja: "学甲" },
  "安南": { en: "Annan", ja: "安南" },
  "宜蘭": { en: "Yilan", ja: "宜蘭" },
  "富里": { en: "Fuli", ja: "富里" },
  "寶僑": { en: "Baoqiao", ja: "宝僑" },
  "將軍": { en: "Jiangjun", ja: "将軍" },
  "將軍驛站": { en: "Jiangjun Station", ja: "将軍駅站" },
  "小港": { en: "Xiaogang", ja: "小港" },
  "山線鐵路自行車道": { en: "Mountain Line Railway Bikeway", ja: "山線鉄道自転車道" },
  "山腳路": { en: "Shanjiao Road", ja: "山脚路" },
  "崇德路": { en: "Chongde Road", ja: "崇徳路" },
  "崇文國小": { en: "Chongwen Elementary School", ja: "崇文小学校" },
  "左營高中": { en: "Zuoying Senior High School", ja: "左営高校" },
  "後壁": { en: "Houbi", ja: "後壁" },
  "恆春": { en: "Hengchun", ja: "恒春" },
  "恆春休息日": { en: "Hengchun rest day", ja: "恒春休息日" },
  "恆春到左營高中": { en: "Hengchun to Zuoying Senior High School", ja: "恒春から左営高校" },
  "恆春國小": { en: "Hengchun Elementary School", ja: "恒春小学校" },
  "恆春轉運站": { en: "Hengchun Bus Transfer Station", ja: "恒春転運站" },
  "斗六": { en: "Douliu", ja: "斗六" },
  "斗南": { en: "Dounan", ja: "斗南" },
  "新城": { en: "Xincheng", ja: "新城" },
  "新城到中原國小": { en: "Xincheng to Zhongyuan Elementary School", ja: "新城から中原小学校" },
  "新城車站": { en: "Xincheng Station", ja: "新城駅" },
  "新埔": { en: "Xinpu", ja: "新埔" },
  "新店": { en: "Xindian", ja: "新店" },
  "新店到羅東國中": { en: "Xindian to Luodong Junior High School", ja: "新店から羅東国中" },
  "新店溪右岸自行車道": { en: "Xindian River Right Bank Bikeway", ja: "新店溪右岸自転車道" },
  "新月橋": { en: "Crescent Bridge", ja: "新月橋" },
  "新生國中": { en: "Xinsheng Junior High School", ja: "新生国中" },
  "新竹": { en: "Hsinchu", ja: "新竹" },
  "新竹到北新國小": { en: "Hsinchu to Beixin Elementary School", ja: "新竹から北新小学校" },
  "新莊": { en: "Xinzhuang", ja: "新荘" },
  "日月潭": { en: "Sun Moon Lake", ja: "日月潭" },
  "景美": { en: "Jingmei", ja: "景美" },
  "景美溪河濱自行車道": { en: "Jingmei River Riverside Bikeway", ja: "景美溪河濱自転車道" },
  "東港": { en: "Donggang", ja: "東港" },
  "東源": { en: "Dongyuan", ja: "東源" },
  "板橋": { en: "Banqiao", ja: "板橋" },
  "枋寮": { en: "Fangliao", ja: "枋寮" },
  "林內": { en: "Linnei", ja: "林内" },
  "林園": { en: "Linyuan", ja: "林園" },
  "梓官": { en: "Ziguan", ja: "梓官" },
  "楓港": { en: "Fenggang", ja: "楓港" },
  "楠梓": { en: "Nanzi", ja: "楠梓" },
  "民雄": { en: "Minxiong", ja: "民雄" },
  "水上": { en: "Shuishang", ja: "水上" },
  "水里": { en: "Shuili", ja: "水里" },
  "永安": { en: "Yong'an", ja: "永安" },
  "池上": { en: "Chishang", ja: "池上" },
  "溪南國小": { en: "Xinan Elementary School", ja: "溪南小学校" },
  "潮州國小": { en: "Chaozhou Elementary School", ja: "潮州小学校" },
  "牡丹": { en: "Mudan", ja: "牡丹" },
  "玉里": { en: "Yuli", ja: "玉里" },
  "玉里到新生國中": { en: "Yuli to Xinsheng Junior High School", ja: "玉里から新生国中" },
  "玉里高中": { en: "Yuli Senior High School", ja: "玉里高校" },
  "瑞穗": { en: "Ruisui", ja: "瑞穂" },
  "知本": { en: "Zhiben", ja: "知本" },
  "石門水庫": { en: "Shimen Reservoir", ja: "石門ダム" },
  "礁溪": { en: "Jiaoxi", ja: "礁溪" },
  "社寮": { en: "Sheliao", ja: "社寮" },
  "竹北": { en: "Zhubei", ja: "竹北" },
  "竹南": { en: "Zhunan", ja: "竹南" },
  "竹山": { en: "Zhushan", ja: "竹山" },
  "統埔": { en: "Tongpu", ja: "統埔" },
  "縣118": { en: "County Route 118", ja: "県道118号" },
  "縣172": { en: "County Route 172", ja: "県道172号" },
  "縣199": { en: "County Route 199", ja: "県道199号" },
  "縣道193": { en: "County Route 193", ja: "県道193号" },
  "羅東==== 新城車站": { en: "Luodong ==== Xincheng Station", ja: "羅東 ==== 新城駅" },
  "羅東國中": { en: "Luodong Junior High School", ja: "羅東国中" },
  "美和": { en: "Meihe", ja: "美和" },
  "臺中": { en: "Taichung", ja: "台中" },
  "臺體體育場": { en: "NTUS Stadium", ja: "台体体育場" },
  "花蓮": { en: "Hualien", ja: "花蓮" },
  "花蓮休息日": { en: "Hualien rest day", ja: "花蓮休息日" },
  "花蓮到玉里高中": { en: "Hualien to Yuli Senior High School", ja: "花蓮から玉里高校" },
  "花蓮市": { en: "Hualien City", ja: "花蓮市" },
  "苓子寮": { en: "Lingziliao", ja: "苓子寮" },
  "苗28": { en: "Miaoli Route 28", ja: "苗28線" },
  "苗栗": { en: "Miaoli", ja: "苗栗" },
  "苗栗到培英國中": { en: "Miaoli to Peiying Junior High School", ja: "苗栗から培英国中" },
  "苗栗濱海自行車道": { en: "Miaoli Coastal Bikeway", ja: "苗栗濱海自転車道" },
  "苗栗高中": { en: "Miaoli Senior High School", ja: "苗栗高校" },
  "茄萣": { en: "Qieding", ja: "茄萣" },
  "草屯": { en: "Caotun", ja: "草屯" },
  "菁寮": { en: "Jingliao", ja: "菁寮" },
  "華江橋自行車便道": { en: "Huajiang Bridge Bike Path", ja: "華江橋自転車道" },
  "萬榮": { en: "Wanrong", ja: "万栄" },
  "萬華": { en: "Wanhua", ja: "万華" },
  "豐原": { en: "Fengyuan", ja: "豊原" },
  "豐原大道": { en: "Fengyuan Boulevard", ja: "豊原大道" },
  "豐科路": { en: "Fengke Road", ja: "豊科路" },
  "貓貍山公園": { en: "Maolishan Park", ja: "猫狸山公園" },
  "車城": { en: "Checheng", ja: "車城" },
  "達仁": { en: "Daren", ja: "達仁" },
  "銅鑼": { en: "Tongluo", ja: "銅鑼" },
  "關山": { en: "Guanshan", ja: "関山" },
  "集集": { en: "Jiji", ja: "集集" },
  "霧峰": { en: "Wufeng", ja: "霧峰" },
  "頭城": { en: "Toucheng", ja: "頭城" },
  "高雄左營": { en: "Kaohsiung Zuoying", ja: "高雄左営" },
  "高雄左營到崇文國小": { en: "Kaohsiung Zuoying to Chongwen Elementary School", ja: "高雄左営から崇文小学校" },
  "魚池": { en: "Yuchi", ja: "魚池" },
  "鳳林": { en: "Fenglin", ja: "鳳林" },
  "鶯歌": { en: "Yingge", ja: "鶯歌" },
  "鹽水": { en: "Yanshui", ja: "塩水" },
  "鹿野": { en: "Luye", ja: "鹿野" },
  "龍潭": { en: "Longtan", ja: "龍潭" },
};

export function localizedRouteText(value: string, language: RouteTextLanguage): string {
  if (language === "zh") {
    return value;
  }

  const translated = routeTextTranslations[value]?.[language];
  return translated ?? value;
}

export function localizedWeekday(value: string, language: RouteTextLanguage): string {
  return weekdayTranslations[value]?.[language] ?? value;
}
